
import fs from 'fs';
import path from 'path';

const HOTSPOTS_FILE = 'src/data/hotspots.json';
const ASSETS_DIR = 'public/assets/Museum Kota Makassar';
const OUTPUT_FILE = 'src/data/sceneMap.js';

// Load hotspots
const hotspotsRaw = fs.readFileSync(HOTSPOTS_FILE, 'utf8');
const hotspotsData = JSON.parse(hotspotsRaw);
const hotspotIds = Object.keys(hotspotsData);

console.log(`Loaded ${hotspotIds.length} hotspot IDs.`);

// Scan assets directory
if (!fs.existsSync(ASSETS_DIR)) {
    console.error(`Directory not found: ${ASSETS_DIR}`);
    process.exit(1);
}

const files = fs.readdirSync(ASSETS_DIR);
console.log(`Found ${files.length} files in assets.`);

const sceneMap = {};
let matchCount = 0;

files.forEach(file => {
    if (!file.endsWith('.jpg')) return;

    // Extract hex suffix: "001_Name_HEX.jpg" -> "HEX"
    // Assuming format is always ..._HEX.jpg where HEX is 6 chars
    const match = file.match(/_([0-9A-F]{6})\.jpg$/i);
    if (match) {
        const shortHex = match[1];

        // Find corresponding ID in hotspots
        // The ID should match ...shortHex... or something similar.
        // Let's assume the ID *contains* this hex sequence.

        const matchedId = hotspotIds.find(id => id.includes(shortHex));

        if (matchedId) {
            sceneMap[matchedId] = {
                path: `assets/Museum Kota Makassar/${file}`,
                shortHex: shortHex
            };
            matchCount++;
        } else {
            console.warn(`No match found for file: ${file} (Hex: ${shortHex})`);
        }
    } else {
        console.warn(`Skipping file with unexpected format: ${file}`);
    }
});

console.log(`Mapped ${matchCount} scenes.`);

// Generate JS output
const fileContent = `// Auto-generated by generate_scene_map.js
export const SCENE_MAP = ${JSON.stringify(sceneMap, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Wrote map to ${OUTPUT_FILE}`);
